from django.urls import path

from .market_views import (
    AdminAnalyticsView,
    AdminBulkDeleteView,
    AdminMarketActivityView,
    AdminMarketCreateView,
    AdminMarketDetailView,
    AdminMarketListView,
    AdminMarketPositionsView,
    AdminMarketResolveView,
    AdminRiskView,
    LegacyBetView,
    LegacyBitcoinMarketView,
    LegacyBitcoinPriceView,
    LegacyMarketChatView,
    LegacyMarketDetailsView,
    LiquidityCompatibilityView,
    MarketAvailabilityView,
    MarketDetailView,
    MarketLatestPriceView,
    MarketListView,
    PolymarketSyncImportView,
    PolymarketSyncPreviewView,
    PolymarketSyncRunView,
)
from users.views import dashboard_data_view, history_data_view

urlpatterns = [
    path('', MarketListView.as_view(), name='legacy-market-list'),
    path('markets/', MarketListView.as_view(), name='legacy-market-list-collection'),
    path('markets/<str:external_id>/latest/', MarketLatestPriceView.as_view(), name='legacy-market-latest-price'),
    path('markets/<str:external_id>/', MarketDetailView.as_view(), name='legacy-market-detail'),
    path('markets/<str:external_id>/trades/', MarketDetailView.as_view(), name='legacy-market-trades'),
    path('markets/<str:external_id>/price-history/', MarketDetailView.as_view(), name='legacy-market-price-history'),
    path('markets/<str:external_id>/positions/', MarketDetailView.as_view(), name='legacy-market-positions'),
    path('markets/search/', MarketListView.as_view(), name='legacy-market-search'),
    path('dashboard/', dashboard_data_view, name='legacy-dashboard-data'),
    path('history/', history_data_view, name='legacy-history-data'),
    path('admin/markets/', AdminMarketListView.as_view(), name='legacy-admin-market-list'),
    path('admin/markets/<int:market_id>/', AdminMarketDetailView.as_view(), name='legacy-admin-market-detail'),
    path('admin/markets/<int:market_id>/positions/', AdminMarketPositionsView.as_view(), name='legacy-admin-market-positions'),
    path('admin/markets/<int:market_id>/activity/', AdminMarketActivityView.as_view(), name='legacy-admin-market-activity'),
    path('admin/create/', AdminMarketCreateView.as_view(), name='legacy-admin-create-market'),
    path('admin/resolve/', AdminMarketResolveView.as_view(), name='legacy-admin-resolve-market'),
    path('admin/bulk-delete/', AdminBulkDeleteView.as_view(), name='legacy-admin-bulk-delete'),
    path('admin/analytics/', AdminAnalyticsView.as_view(), name='legacy-admin-analytics'),
    path('admin/risk/', AdminRiskView.as_view(), name='legacy-admin-risk'),
    path('admin/polymarket/sync-preview/', PolymarketSyncPreviewView.as_view(), name='legacy-polymarket-sync-preview'),
    path('admin/polymarket/sync/', PolymarketSyncImportView.as_view(), name='legacy-polymarket-sync-import'),
    path('admin/polymarket/run-sync/', PolymarketSyncRunView.as_view(), name='legacy-polymarket-sync-run'),
    path('bitcoin/', LegacyBitcoinMarketView.as_view(), name='legacy-bitcoin-market'),
    path('bitcoin/price/', LegacyBitcoinPriceView.as_view(), name='legacy-bitcoin-price'),
    path('<int:market_id>/details/', LegacyMarketDetailsView.as_view(), name='legacy-market-details'),
    path('<int:market_id>/chat/', LegacyMarketChatView.as_view(), name='legacy-market-chat'),
    path('<int:market_id>/available-shares/', MarketAvailabilityView.as_view(), name='legacy-market-available-shares'),
    path('<int:market_id>/add-liquidity/', LiquidityCompatibilityView.as_view(), name='legacy-market-add-liquidity'),
    path('liquidity/positions/', LiquidityCompatibilityView.as_view(), name='legacy-liquidity-positions'),
    path('liquidity/analytics/', LiquidityCompatibilityView.as_view(), name='legacy-liquidity-analytics'),
    path('liquidity/fee-analytics/', LiquidityCompatibilityView.as_view(), name='legacy-liquidity-fee-analytics'),
    path('liquidity/pool-stats/', LiquidityCompatibilityView.as_view(), name='legacy-liquidity-pool-stats'),
    path('liquidity/risk-score/', LiquidityCompatibilityView.as_view(), name='legacy-liquidity-risk-score'),
    path('liquidity/deposit/', LiquidityCompatibilityView.as_view(), name='legacy-liquidity-deposit'),
    path('liquidity/withdraw/', LiquidityCompatibilityView.as_view(), name='legacy-liquidity-withdraw'),
    path('liquidity/claim-fees/', LiquidityCompatibilityView.as_view(), name='legacy-liquidity-claim-fees'),
    path('bet/', LegacyBetView.as_view(), name='legacy-bet'),
]
