from django.urls import path
from .views import PlaceOrderView, PolymarketFillWebhookView, PolymarketResolutionWebhookView
from .category_views import CategoryListView
from .market_views import (
    MarketListView,
    MarketDetailView,
    MarketLatestPriceView,
    PolymarketSyncPreviewView,
    PolymarketSyncImportView,
    PolymarketSyncRunView,
    LegacyMarketDetailsView,
    LegacyMarketChatView,
    LegacyBitcoinMarketView,
    LegacyBitcoinPriceView,
    LegacyBetView,
    AdminMarketListView,
    AdminMarketDetailView,
    AdminMarketCreateView,
    AdminMarketResolveView,
    AdminMarketPositionsView,
    AdminMarketActivityView,
    AdminAnalyticsView,
    AdminRiskView,
    AdminBulkDeleteView,
)
from users.views import dashboard_data_view, history_data_view

urlpatterns = [
    path('orders/place/', PlaceOrderView.as_view(), name='place-order'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('webhooks/polymarket-fills/', PolymarketFillWebhookView.as_view(), name='polymarket-fill-webhook'),
    path('webhooks/polymarket-resolution/', PolymarketResolutionWebhookView.as_view(), name='polymarket-resolution-webhook'),
    path('', MarketListView.as_view(), name='legacy-market-list'),
    path('markets/', MarketListView.as_view(), name='market-list'),
    path('markets/<str:external_id>/latest/', MarketLatestPriceView.as_view(), name='market-latest-price'),
    path('markets/<str:external_id>/', MarketDetailView.as_view(), name='market-detail'),
    path('markets/<str:external_id>/trades/', MarketDetailView.as_view(), name='market-trades'),
    path('markets/<str:external_id>/price-history/', MarketDetailView.as_view(), name='market-price-history'),
    path('markets/<str:external_id>/positions/', MarketDetailView.as_view(), name='market-positions'),
    path('markets/search/', MarketListView.as_view(), name='market-search'),
    path('dashboard/', dashboard_data_view, name='legacy-dashboard-data'),
    path('history/', history_data_view, name='legacy-history-data'),
    path('admin/markets/', AdminMarketListView.as_view(), name='legacy-admin-market-list'),
    path('admin/markets/<int:market_id>/', AdminMarketDetailView.as_view(), name='legacy-admin-market-detail'),
    path('admin/markets/<int:market_id>/positions/', AdminMarketPositionsView.as_view(), name='legacy-admin-market-positions'),
    path('admin/markets/<int:market_id>/activity/', AdminMarketActivityView.as_view(), name='legacy-admin-market-activity'),
    path('admin/create/', AdminMarketCreateView.as_view(), name='legacy-admin-create-market'),
    path('admin/resolve/', AdminMarketResolveView.as_view(), name='legacy-admin-resolve-market'),
    path('admin/bulk-delete/', AdminBulkDeleteView.as_view(), name='legacy-admin-bulk-delete'),
    path('admin/analytics/', AdminAnalyticsView.as_view(), name='legacy-admin-analytics'),
    path('admin/risk/', AdminRiskView.as_view(), name='legacy-admin-risk'),
    path('admin/polymarket/sync-preview/', PolymarketSyncPreviewView.as_view(), name='polymarket-sync-preview'),
    path('admin/polymarket/sync/', PolymarketSyncImportView.as_view(), name='polymarket-sync-import'),
    path('admin/polymarket/run-sync/', PolymarketSyncRunView.as_view(), name='polymarket-sync-run'),
    path('bitcoin/', LegacyBitcoinMarketView.as_view(), name='legacy-bitcoin-market'),
    path('bitcoin/price/', LegacyBitcoinPriceView.as_view(), name='legacy-bitcoin-price'),
    path('<int:market_id>/details/', LegacyMarketDetailsView.as_view(), name='legacy-market-details'),
    path('<int:market_id>/chat/', LegacyMarketChatView.as_view(), name='legacy-market-chat'),
    path('bet/', LegacyBetView.as_view(), name='legacy-bet'),
]
