# Generated by Django 6.0.6 on 2026-06-16 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_phone_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Unique username displayed as @username throughout the platform', max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be 3-30 characters and contain only letters, numbers, underscores, or hyphens.', regex='^[a-zA-Z0-9_-]{3,30}$')]),
        ),
    ]
