# Generated by Django 6.0.6 on 2026-06-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0016_liquiditypool_liquidityprovider_feedistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='trading_fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
    ]
