# Generated by Codex on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0017_bet_total_cost_bet_trading_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='subcategory',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
