# Generated by Django 6.0.6 on 2026-06-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0002_market_approval_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='question',
            field=models.TextField(blank=True, help_text='The actual market question', null=True),
        ),
    ]
