# Generated by Django 6.0.6 on 2026-06-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0003_market_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Politics', 'Politics'), ('Economy', 'Economy'), ('Crypto', 'Crypto'), ('Technology', 'Technology'), ('Environment', 'Environment'), ('Geopolitics', 'Geopolitics'), ('Other', 'Other')], db_index=True, default='Other', max_length=50),
        ),
    ]
