# Generated by Django 6.0.6 on 2026-06-13 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0004_market_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='parent_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='brokerage.market'),
        ),
    ]
