# Generated by Django 6.0.6 on 2026-06-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0006_polymarket_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='subcategory',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
