# Generated by Django 6.0.6 on 2026-07-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0009_chatmessage'),
        ('support', '0003_chatmessage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='support_cha_market__89e5e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='support_cha_user_id_5684ae_idx',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('brokerage.chatmessage',),
        ),
    ]
