# Generated by Django 6.0.6 on 2026-07-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_remove_chatmessage_support_cha_market__89e5e2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('ACCOUNT', 'Account'), ('PAYMENT', 'Payment'), ('TECHNICAL', 'Technical'), ('FEATURE_REQUEST', 'Feature Request')], default='GENERAL', max_length=30),
        ),
    ]
